export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_NAME = 'GET_NAME';
export const GET_ACTIVITIES = 'GET_ACTIVITIES';
export const GET_COUNTRYBYID = 'GET_COUNTRYBYID';
export const FILTER = 'FILTER';
export const ORDER = 'ORDER';
export const POBLATION = 'POBLATION';
export const CONTINENT = 'CONTINENT';
export const ACTIVITY = 'ACTIVITY';
export const ADD_COUNTRY_ACTIVITY = 'ADD_COUNTRY_ACTIVITY';
export const REMOVE_COUNTRY_ACTIVITY = 'REMOVE_COUNTRY_ACTIVITY';

